// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// POR FAVOR, FORNEÇA O NOVO URL E CHAVE AQUI
const SUPABASE_URL = "https://SEU_NOVO_URL.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "SUA_NOVA_CHAVE_ANONIMA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);